[tools]
node = "lts"
neovim = "stable"
eza = "latest"
yazi = "latest"
delta = "latest"
"aqua:bootandy/dust" = "latest"
"aqua:chmln/sd" = "latest"
lazygit = "latest"
starship = "latest"
ripgrep = "latest"
fd = "latest"
bat = "latest"
fzf = "latest"
zoxide = "latest"
just = "latest"
btop = "latest"
"aqua:schollz/croc" = "latest"
"aqua:tealdeer-rs/tealdeer" = "latest"
"aqua:sharkdp/hyperfine" = "latest"
"aqua:muesli/duf" = "latest"
"npm:@openai/codex" = "latest"
gcloud = "latest"
uv = "latest"
